# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    scara_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

scara_controller:
  ros__parameters:
    joints:
      - 2_1brazo_robotico_link_joint
      - 3_1brazo_robotico_link_joint
      - 5brazo_robotico_link_joint
      - 5mano_brazo_robotico_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

gripper_controller:
  ros__parameters:
    joints:
      - 5mano_derecha_brazo_robotico_link_joint
      - 5mano_izquierda_brazo_robotico_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true